In [4]:
import logging
import cv2
import numpy as np
import copy

logging.basicConfig(level=logging.DEBUG, format='%(asctime)-15s %(levelname)s \t%(message)s')

def draw_crosshair(image, center, width, color):
    print(center)
    cv2.line(image, (center[0] - width//2, center[1]), (center[0] + width//2, center[1]), color)
    cv2.line(image, (center[0], center[1] - width//2), (center[0], center[1] + width//2), color)

logging.info("compute_homography.py main()")
image_filepath = "./Images/checkerboard.png"
features_mm_to_pixels_dict =  {(0, 0): (192, 801, ),
                              (214.2, 0): (937, 652),
                              (214.2, 178.5): (798, 67),
                              (0, 178.5): (101, 197)}
A = np.zeros((2 * len(features_mm_to_pixels_dict), 6), dtype=float)
b = np.zeros((2 * len(features_mm_to_pixels_dict), 1), dtype=float)
index = 0
for XY, xy in features_mm_to_pixels_dict.items():
    X = XY[0]
    Y = XY[1]
    x = xy[0]
    y = xy[1]
    A[2 * index, 0] = x
    A[2 * index, 1] = y
    A[2 * index, 2] = 1
    A[2 * index + 1, 3] = x
    A[2 * index + 1, 4] = y
    A[2 * index + 1, 5] = 1
    b[2 * index, 0] = X
    b[2 * index + 1, 0] = Y
    index += 1
    print(A)
    print(b)
# A @ x = b
x, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)

pixels_to_mm_transformation_mtx = np.array([[x[0, 0], x[1, 0], x[2, 0]], [x[3, 0], x[4, 0], x[5, 0]], [0, 0, 1]])
logging.debug("main(): pixels_to_mm_transformation_mtx = \n{}".format(pixels_to_mm_transformation_mtx))

test_xy_1 = (399, 500, 1)
test_XY_1 = pixels_to_mm_transformation_mtx @ test_xy_1
logging.info("main(): test_xy_1 = {}; test_XY_1 = {}".format(test_xy_1, test_XY_1))

mm_to_pixels_transformation_mtx = np.linalg.inv(pixels_to_mm_transformation_mtx)
test_XY_2 = (107.1, 107.1, 1)
test_xy_2 = mm_to_pixels_transformation_mtx @ test_XY_2
image = cv2.imread(image_filepath)
annotated_img = copy.deepcopy(image)
draw_crosshair(annotated_img, (round(test_xy_2[0]), round(test_xy_2[1])), 60, (0, 0, 255))
cv2.imwrite("./outputs/annotated.png", annotated_img)

2022-09-17 15:55:54,076 INFO 	compute_homography.py main()
2022-09-17 15:55:54,080 DEBUG 	main(): pixels_to_mm_transformation_mtx = 
[[ 2.86046413e-01 -5.52348998e-02 -1.42159506e+01]
 [-5.60587484e-02 -2.89389723e-01  2.41892324e+02]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
2022-09-17 15:55:54,081 INFO 	main(): test_xy_1 = (399, 500, 1); test_XY_1 = [72.29911825 74.83002195  1.        ]


[[192. 801.   1.   0.   0.   0.]
 [  0.   0.   0. 192. 801.   1.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[192. 801.   1.   0.   0.   0.]
 [  0.   0.   0. 192. 801.   1.]
 [937. 652.   1.   0.   0.   0.]
 [  0.   0.   0. 937. 652.   1.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
[[  0. ]
 [  0. ]
 [214.2]
 [  0. ]
 [  0. ]
 [  0. ]
 [  0. ]
 [  0. ]]
[[192. 801.   1.   0.   0.   0.]
 [  0.   0.   0. 192. 801.   1.]
 [937. 652.   1.   0.   0.   0.]
 [  0.   0.   0. 937. 652.   1.]
 [798.  67.   1.   0.   0.   0.]
 [  0.   0.   0. 798.  67.   1.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
[[  0. ]
 [  0. ]
 [214.2]
 [  0. ]
 [214.2]
 [178.5]
 [  0. ]
 [  0. ]]
[[192. 801

True

In [2]:
import logging
import cv2
import numpy as np
import copy

logging.basicConfig(level=logging.DEBUG, format='%(asctime)-15s %(levelname)s \t%(message)s')

def draw_crosshair(image, center, width, color):
    print(center)
    cv2.line(image, (center[0] - width//2, center[1]), (center[0] + width//2, center[1]), color)
    cv2.line(image, (center[0], center[1] - width//2), (center[0], center[1] + width//2), color)

logging.info("compute_homography.py main()")
image_filepath = "./Images/0.png"
features_mm_to_pixels_dict =  {(0., 0.): (178.97382,  42.35252, ),
                              (132.,   0.): (405.64944,  41.79083),
                              (132.,  66.): (407.20145, 155.39421),
                              (0., 66.): (178.95978, 156.45543)}
A = np.zeros((2 * len(features_mm_to_pixels_dict), 6), dtype=float)
b = np.zeros((2 * len(features_mm_to_pixels_dict), 1), dtype=float)
index = 0
for XY, xy in features_mm_to_pixels_dict.items():
    X = XY[0]
    Y = XY[1]
    x = xy[0]
    y = xy[1]
    A[2 * index, 0] = x
    A[2 * index, 1] = y
    A[2 * index, 2] = 1
    A[2 * index + 1, 3] = x
    A[2 * index + 1, 4] = y
    A[2 * index + 1, 5] = 1
    b[2 * index, 0] = X
    b[2 * index + 1, 0] = Y
    index += 1
    print(A)
    print(b)
# A @ x = b
x, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)

pixels_to_mm_transformation_mtx = np.array([[x[0, 0], x[1, 0], x[2, 0]], [x[3, 0], x[4, 0], x[5, 0]], [0, 0, 1]])
logging.debug("main(): pixels_to_mm_transformation_mtx = \n{}".format(pixels_to_mm_transformation_mtx))

test_xy_1 = (399, 500, 1)
test_XY_1 = pixels_to_mm_transformation_mtx @ test_xy_1
logging.info("main(): test_xy_1 = {}; test_XY_1 = {}".format(test_xy_1, test_XY_1))

mm_to_pixels_transformation_mtx = np.linalg.inv(pixels_to_mm_transformation_mtx)
test_XY_2 = (132, 66, 1)
test_xy_2 = mm_to_pixels_transformation_mtx @ test_XY_2
image = cv2.imread(image_filepath)
annotated_img = copy.deepcopy(image)
draw_crosshair(annotated_img, (round(test_xy_2[0]), round(test_xy_2[1])), 60, (0, 0, 255))
cv2.imwrite("./outputs/annotated2.png", annotated_img)

2022-09-17 20:38:39,799 INFO 	compute_homography.py main()
2022-09-17 20:38:39,803 DEBUG 	main(): pixels_to_mm_transformation_mtx = 
[[ 5.80304414e-01 -3.91080651e-03 -1.03465689e+02]
 [ 2.07016105e-03  5.79677422e-01 -2.49929770e+01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
2022-09-17 20:38:39,805 INFO 	main(): test_xy_1 = (399, 500, 1); test_XY_1 = [126.12036904 265.6717281    1.        ]


[[178.97382  42.35252   1.        0.        0.        0.     ]
 [  0.        0.        0.      178.97382  42.35252   1.     ]
 [  0.        0.        0.        0.        0.        0.     ]
 [  0.        0.        0.        0.        0.        0.     ]
 [  0.        0.        0.        0.        0.        0.     ]
 [  0.        0.        0.        0.        0.        0.     ]
 [  0.        0.        0.        0.        0.        0.     ]
 [  0.        0.        0.        0.        0.        0.     ]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[178.97382  42.35252   1.        0.        0.        0.     ]
 [  0.        0.        0.      178.97382  42.35252   1.     ]
 [405.64944  41.79083   1.        0.        0.        0.     ]
 [  0.        0.        0.      405.64944  41.79083   1.     ]
 [  0.        0.        0.        0.        0.        0.     ]
 [  0.        0.        0.        0.        0.        0.     ]
 [  0.        0.        0.        0.        0.        0.     ]
 [  0

True

In [17]:
import cv2
import numpy as np
from decimal import Decimal

prevX,prevY=-1,-1
def printCoordinate(event, x, y, flags, params):
    global prevX,prevY
    if event==cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img,(x,y),3,(0,0,255),-1)
        
        font=cv2.FONT_HERSHEY_PLAIN
        planeMatrix = (x, y, 1)
        print(planeMatrix)
        worldMatrix = pixels_to_mm_transformation_mtx @ planeMatrix
        print(worldMatrix)
        print(x)
        print(y)
        strXY='(' + str(round(Decimal(str(worldMatrix[0])), 2)) + ',' + str(round(Decimal(str(worldMatrix[0])), 2))+')'
        cv2.putText(img,strXY,(x+10,y-10),font,1,(255,0,255),2)
        if prevX==-1 and prevY==-1:
            prevX,prevY=x,y
        else:
            prevX,prevY=-1,-1
        cv2.imshow("image",img)
img = cv2.imread('Images/0.png')

cv2.imshow("image",img)
cv2.setMouseCallback("image",printCoordinate)
cv2.waitKey()
cv2.destroyAllWindows()

(179, 43, 1)
[0.24063661 0.30371099 1.        ]
179
43
(218, 80, 1)
[22.7278089  21.83251187  1.        ]
218
80
(256, 118, 1)
[44.63076597 43.93892001  1.        ]
256
118
(292, 157, 1)
[65.36920341 66.62086525  1.        ]
292
157
(334, 194, 1)
[89.59728894 88.15587662  1.        ]
334
194
