In [1]:
import numpy as np
import cv2 as cv
import glob

In [2]:
# FIND CHESSBOARD CORNERS - OBJECT POINTS AND IMAGE POINTS

chessboardSize = (7, 4)
frameSize = (640, 480)

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

In [3]:
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((chessboardSize[0] * chessboardSize[1], 3), np.float32)
objp[:,:2] = np.mgrid[0:chessboardSize[0],0:chessboardSize[1]].T.reshape(-1,2)

size_of_chessboard_squares_mm = 22
objp = objp * size_of_chessboard_squares_mm

In [38]:
objp

array([[  0.,   0.,   0.],
       [ 22.,   0.,   0.],
       [ 44.,   0.,   0.],
       [ 66.,   0.,   0.],
       [ 88.,   0.,   0.],
       [110.,   0.,   0.],
       [132.,   0.,   0.],
       [  0.,  22.,   0.],
       [ 22.,  22.,   0.],
       [ 44.,  22.,   0.],
       [ 66.,  22.,   0.],
       [ 88.,  22.,   0.],
       [110.,  22.,   0.],
       [132.,  22.,   0.],
       [  0.,  44.,   0.],
       [ 22.,  44.,   0.],
       [ 44.,  44.,   0.],
       [ 66.,  44.,   0.],
       [ 88.,  44.,   0.],
       [110.,  44.,   0.],
       [132.,  44.,   0.],
       [  0.,  66.,   0.],
       [ 22.,  66.,   0.],
       [ 44.,  66.,   0.],
       [ 66.,  66.,   0.],
       [ 88.,  66.,   0.],
       [110.,  66.,   0.],
       [132.,  66.,   0.]], dtype=float32)

In [45]:
list1 = []

In [46]:
for elements in objp:
    elements = elements[:2] 
    list1.append(elements)

In [47]:
list1

[array([0., 0.], dtype=float32),
 array([22.,  0.], dtype=float32),
 array([44.,  0.], dtype=float32),
 array([66.,  0.], dtype=float32),
 array([88.,  0.], dtype=float32),
 array([110.,   0.], dtype=float32),
 array([132.,   0.], dtype=float32),
 array([ 0., 22.], dtype=float32),
 array([22., 22.], dtype=float32),
 array([44., 22.], dtype=float32),
 array([66., 22.], dtype=float32),
 array([88., 22.], dtype=float32),
 array([110.,  22.], dtype=float32),
 array([132.,  22.], dtype=float32),
 array([ 0., 44.], dtype=float32),
 array([22., 44.], dtype=float32),
 array([44., 44.], dtype=float32),
 array([66., 44.], dtype=float32),
 array([88., 44.], dtype=float32),
 array([110.,  44.], dtype=float32),
 array([132.,  44.], dtype=float32),
 array([ 0., 66.], dtype=float32),
 array([22., 66.], dtype=float32),
 array([44., 66.], dtype=float32),
 array([66., 66.], dtype=float32),
 array([88., 66.], dtype=float32),
 array([110.,  66.], dtype=float32),
 array([132.,  66.], dtype=float32)]

In [48]:
np.shape(list1)

(28, 2)

In [42]:
np.shape(objp)

(28, 3)

In [4]:
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

In [8]:
images = glob.glob('Images/*.png')


In [9]:
images

['Images\\0.png',
 'Images\\1.png',
 'Images\\10.png',
 'Images\\11.png',
 'Images\\12.png',
 'Images\\13.png',
 'Images\\2.png',
 'Images\\3.png',
 'Images\\4.png',
 'Images\\5.png',
 'Images\\6.png',
 'Images\\7.png',
 'Images\\8.png',
 'Images\\9.png']

In [33]:
imgTest = cv.imread(images[0])
gray = cv.cvtColor(imgTest, cv.COLOR_BGR2GRAY)

# Find the chess board corners
ret, corners = cv.findChessboardCorners(gray, chessboardSize, None)
print(corners)

# If found, add object points, image points (after refining them)
if ret == True:

    objpoints.append(objp)
    corners2 = cv.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
    imgpoints.append(corners)

    # Draw and display the corners
    cv.drawChessboardCorners(img, chessboardSize, corners2, ret)
    cv.imshow('img', img)
    cv.waitKey(1)

[[[179.19336   42.298363]]

 [[216.73253   41.580166]]

 [[255.04602   41.27148 ]]

 [[292.8215    40.670948]]

 [[330.72433   40.6529  ]]

 [[368.6828    41.279816]]

 [[405.86884   41.745533]]

 [[179.21057   80.37096 ]]

 [[217.02658   79.93684 ]]

 [[255.2827    79.57579 ]]

 [[293.23972   79.127556]]

 [[331.1151    78.78044 ]]

 [[369.249     79.07783 ]]

 [[406.47736   79.69517 ]]

 [[179.17502  118.38547 ]]

 [[217.21713  118.167984]]

 [[255.35925  117.559906]]

 [[293.47543  117.42196 ]]

 [[331.45303  117.07461 ]]

 [[369.4241   117.40093 ]]

 [[406.7595   117.524635]]

 [[179.08577  156.40198 ]]

 [[217.22437  156.2774  ]]

 [[255.54582  155.92007 ]]

 [[293.63318  155.57129 ]]

 [[331.75427  155.47502 ]]

 [[369.70502  155.42389 ]]

 [[407.52652  155.43407 ]]]


In [55]:
corners3 = np.squeeze(corners2)

In [56]:
np.shape(corners3)

(28, 2)

In [84]:
mylist = np.zeros((28,2))
print(mylist)
print(mylist[27][0])

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0.0


In [89]:
mylist = list(zip(list1, corners3))
print(mylist)

[(array([0., 0.], dtype=float32), array([178.97382,  42.35252], dtype=float32)), (array([22.,  0.], dtype=float32), array([216.65868 ,  41.672398], dtype=float32)), (array([44.,  0.], dtype=float32), array([254.80519 ,  41.403774], dtype=float32)), (array([66.,  0.], dtype=float32), array([292.71628 ,  40.783855], dtype=float32)), (array([88.,  0.], dtype=float32), array([330.5524 ,  40.75461], dtype=float32)), (array([110.,   0.], dtype=float32), array([368.48297 ,  41.177303], dtype=float32)), (array([132.,   0.], dtype=float32), array([405.64944,  41.79083], dtype=float32)), (array([ 0., 22.], dtype=float32), array([179.10957,  80.46389], dtype=float32)), (array([22., 22.], dtype=float32), array([216.8516 ,  80.01179], dtype=float32)), (array([44., 22.], dtype=float32), array([255.10725,  79.60863], dtype=float32)), (array([66., 22.], dtype=float32), array([293.0102 ,  79.18325], dtype=float32)), (array([88., 22.], dtype=float32), array([330.9741 ,  78.83384], dtype=float32)), (arra

In [90]:
dict(mylist)

TypeError: unhashable type: 'numpy.ndarray'

In [11]:
for image in images:

    img = cv.imread(image)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, chessboardSize, None)
    print(corners)

    # If found, add object points, image points (after refining them)
    if ret == True:

        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners)

        # Draw and display the corners
        cv.drawChessboardCorners(img, chessboardSize, corners2, ret)
        cv.imshow('img', img)
        cv.waitKey(1)


cv.destroyAllWindows()


[[[179.19336   42.298363]]

 [[216.73253   41.580166]]

 [[255.04602   41.27148 ]]

 [[292.8215    40.670948]]

 [[330.72433   40.6529  ]]

 [[368.6828    41.279816]]

 [[405.86884   41.745533]]

 [[179.21057   80.37096 ]]

 [[217.02658   79.93684 ]]

 [[255.2827    79.57579 ]]

 [[293.23972   79.127556]]

 [[331.1151    78.78044 ]]

 [[369.249     79.07783 ]]

 [[406.47736   79.69517 ]]

 [[179.17502  118.38547 ]]

 [[217.21713  118.167984]]

 [[255.35925  117.559906]]

 [[293.47543  117.42196 ]]

 [[331.45303  117.07461 ]]

 [[369.4241   117.40093 ]]

 [[406.7595   117.524635]]

 [[179.08577  156.40198 ]]

 [[217.22437  156.2774  ]]

 [[255.54582  155.92007 ]]

 [[293.63318  155.57129 ]]

 [[331.75427  155.47502 ]]

 [[369.70502  155.42389 ]]

 [[407.52652  155.43407 ]]]
[[[138.65134  154.40866 ]]

 [[174.91014  143.30957 ]]

 [[211.63234  132.14445 ]]

 [[248.07286  121.15468 ]]

 [[284.6393   110.443184]]

 [[321.50702   99.99088 ]]

 [[357.56146   89.817566]]

 [[149.56274  191.42

In [13]:
corners.shape

(28, 1, 2)

In [14]:
############## CALIBRATION #######################################################

ret, cameraMatrix, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, frameSize, None, None)

In [15]:
ret

0.2275612589966608

In [16]:
cameraMatrix

array([[1.21391936e+04, 0.00000000e+00, 3.89640961e+02],
       [0.00000000e+00, 1.22219672e+04, 2.52894248e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [17]:
dist

array([[-4.13238867e+01,  1.02048439e+04, -4.59036175e-02,
        -3.69838757e-01,  2.08965255e+01]])

In [18]:
rvecs

(array([[ 0.04057792],
        [-0.17526104],
        [-0.00614104]]),
 array([[ 0.0068729 ],
        [-0.15504574],
        [-0.28853023]]),
 array([[ 0.10195724],
        [-0.13681426],
        [ 1.38959988]]),
 array([[-0.17535601],
        [ 0.05510473],
        [ 2.52200144]]),
 array([[ 0.22844026],
        [ 0.0078599 ],
        [-3.12694904]]),
 array([[-0.10910741],
        [ 0.10279948],
        [ 1.66954896]]),
 array([[ 0.15271544],
        [ 0.10167642],
        [-1.5833285 ]]),
 array([[ 0.08128766],
        [-0.15110589],
        [ 0.63785043]]),
 array([[ 0.03925673],
        [ 0.10597304],
        [-0.55225334]]),
 array([[ 0.02857393],
        [-0.15222056],
        [-0.04707785]]),
 array([[ 0.07461315],
        [-0.14906949],
        [ 0.51492679]]),
 array([[-0.00571543],
        [-0.13826351],
        [-0.33607269]]),
 array([[-0.04024102],
        [-0.1225401 ],
        [-0.71908092]]),
 array([[ 0.03265395],
        [-0.13835593],
        [ 0.02873779]]),
 array

In [31]:
np.shape(rvecs)

(28, 3, 1)

In [19]:
tvecs

(array([[-119.9115614 ],
        [-120.48802785],
        [6948.7927065 ]]),
 array([[-143.22179012],
        [ -56.17074186],
        [6969.49849283]]),
 array([[ 2.28726588e-01],
        [-8.78156119e+01],
        [ 6.97437974e+03]]),
 array([[  36.63415453],
        [ -12.46739946],
        [7001.98134461]]),
 array([[  33.21303901],
        [  45.55174851],
        [7001.55276473]]),
 array([[ -20.62865794],
        [ -74.46033787],
        [7003.39811358]]),
 array([[-195.29584128],
        [  53.0235204 ],
        [6940.46808229]]),
 array([[ -17.69359214],
        [ -93.52275049],
        [6963.82654729]]),
 array([[-1.77058406e+02],
        [ 6.70913003e+00],
        [ 6.99293640e+03]]),
 array([[ -93.21340133],
        [ -67.88089287],
        [6975.71470319]]),
 array([[ -32.22214537],
        [ -86.91881321],
        [6969.70780555]]),
 array([[-122.76969117],
        [ -20.61456688],
        [6986.83369008]]),
 array([[-136.85842152],
        [  29.34514114],
        [6987.

In [20]:
 ############## UNDISTORTION #####################################################

img = cv.imread('Images/0.png')
h,  w = img.shape[:2]
newCameraMatrix, roi = cv.getOptimalNewCameraMatrix(cameraMatrix, dist, (w,h), 1, (w,h))

In [21]:
# Undistort
dst = cv.undistort(img, cameraMatrix, dist, None, newCameraMatrix)

# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('caliResult1.png', dst)

True

In [22]:
# Undistort with Remapping
mapx, mapy = cv.initUndistortRectifyMap(cameraMatrix, dist, None, newCameraMatrix, (w,h), 5)
dst = cv.remap(img, mapx, mapy, cv.INTER_LINEAR)

# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('caliResult2.png', dst)

True

In [23]:
# Reprojection Error
mean_error = 0

for i in range(len(objpoints)):
    imgpoints2, _ = cv.projectPoints(objpoints[i], rvecs[i], tvecs[i], cameraMatrix, dist)
    error = cv.norm(imgpoints[i], imgpoints2, cv.NORM_L2)/len(imgpoints2)
    mean_error += error

print( "total error: {}".format(mean_error/len(objpoints)))

total error: 0.04134568355964071


In [24]:
objpoints


[array([[  0.,   0.,   0.],
        [ 22.,   0.,   0.],
        [ 44.,   0.,   0.],
        [ 66.,   0.,   0.],
        [ 88.,   0.,   0.],
        [110.,   0.,   0.],
        [132.,   0.,   0.],
        [  0.,  22.,   0.],
        [ 22.,  22.,   0.],
        [ 44.,  22.,   0.],
        [ 66.,  22.,   0.],
        [ 88.,  22.,   0.],
        [110.,  22.,   0.],
        [132.,  22.,   0.],
        [  0.,  44.,   0.],
        [ 22.,  44.,   0.],
        [ 44.,  44.,   0.],
        [ 66.,  44.,   0.],
        [ 88.,  44.,   0.],
        [110.,  44.,   0.],
        [132.,  44.,   0.],
        [  0.,  66.,   0.],
        [ 22.,  66.,   0.],
        [ 44.,  66.,   0.],
        [ 66.,  66.,   0.],
        [ 88.,  66.,   0.],
        [110.,  66.,   0.],
        [132.,  66.,   0.]], dtype=float32),
 array([[  0.,   0.,   0.],
        [ 22.,   0.,   0.],
        [ 44.,   0.,   0.],
        [ 66.,   0.,   0.],
        [ 88.,   0.,   0.],
        [110.,   0.,   0.],
        [132.,   0.,   0.],
   

In [29]:
objpoints[0]

array([[  0.,   0.,   0.],
       [ 22.,   0.,   0.],
       [ 44.,   0.,   0.],
       [ 66.,   0.,   0.],
       [ 88.,   0.,   0.],
       [110.,   0.,   0.],
       [132.,   0.,   0.],
       [  0.,  22.,   0.],
       [ 22.,  22.,   0.],
       [ 44.,  22.,   0.],
       [ 66.,  22.,   0.],
       [ 88.,  22.,   0.],
       [110.,  22.,   0.],
       [132.,  22.,   0.],
       [  0.,  44.,   0.],
       [ 22.,  44.,   0.],
       [ 44.,  44.,   0.],
       [ 66.,  44.,   0.],
       [ 88.,  44.,   0.],
       [110.,  44.,   0.],
       [132.,  44.,   0.],
       [  0.,  66.,   0.],
       [ 22.,  66.,   0.],
       [ 44.,  66.,   0.],
       [ 66.,  66.,   0.],
       [ 88.,  66.,   0.],
       [110.,  66.,   0.],
       [132.,  66.,   0.]], dtype=float32)

In [28]:
np.shape(objpoints)

(28, 28, 3)

In [25]:
imgpoints

[array([[[178.97382 ,  42.35252 ]],
 
        [[216.65868 ,  41.672398]],
 
        [[254.80519 ,  41.403774]],
 
        [[292.71628 ,  40.783855]],
 
        [[330.5524  ,  40.75461 ]],
 
        [[368.48297 ,  41.177303]],
 
        [[405.64944 ,  41.79083 ]],
 
        [[179.10957 ,  80.46389 ]],
 
        [[216.8516  ,  80.01179 ]],
 
        [[255.10725 ,  79.60863 ]],
 
        [[293.0102  ,  79.18325 ]],
 
        [[330.9741  ,  78.83384 ]],
 
        [[368.84995 ,  79.20462 ]],
 
        [[406.1805  ,  79.63734 ]],
 
        [[178.9818  , 118.45157 ]],
 
        [[217.01329 , 118.15479 ]],
 
        [[255.17958 , 117.70993 ]],
 
        [[293.23557 , 117.40103 ]],
 
        [[331.18082 , 117.165535]],
 
        [[369.15427 , 117.3906  ]],
 
        [[406.51746 , 117.5393  ]],
 
        [[178.95978 , 156.45543 ]],
 
        [[217.15138 , 156.28271 ]],
 
        [[255.40164 , 155.90076 ]],
 
        [[293.41022 , 155.64423 ]],
 
        [[331.47397 , 155.45605 ]],
 
        [[36

In [30]:
np.shape(imgpoints)

(28, 28, 1, 2)